config/routes.rb
Rails.application.routes.draw do

  get     '/',                      to: 'home#index',         as: :root
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  get     '/blog',                  to: 'blog#index',         as: :post
  get     '/blog',                  to: 'blog#index',         as: :posts
  get     '/blog/new',              to: 'blog#new',           as: :posts_new
  post    '/blog',                  to: 'blog#create',        as: :posts_create
  get     '/blog/:id',              to: 'blog#show',          as: :posts_show
  get     '/blog/:id/edit',         to: 'blog#edit',          as: :posts_edit
  patch   '/blog/:id',              to: 'blog#update',        as: :posts_update
  delete  '/blog/:id/delete',       to: 'blog#destroy',       as: :posts_destroy

  get     '/shop',                  to: 'shop#index',         as: :product
  get     '/shop',                  to: 'shop#index',         as: :products
  get     '/shop/new',              to: 'shop#new',           as: :products_new
  post    '/shop',                  to: 'shop#create',        as: :products_create
  get     '/shop/:id',              to: 'shop#show',          as: :products_show
  get     '/shop/:id/edit',         to: 'shop#edit',          as: :products_edit
  patch   '/shop/:id',              to: 'shop#update',        as: :products_update
  delete  '/shop/:id/delete',       to: 'shop#destroy',       as: :products_destroy

  get     '/cart',                  to: 'carts#index',         as: :order
  get     '/cart/new',              to: 'carts#new',           as: :order_new
  post    '/cart',                  to: 'carts#create',        as: :order_create
  get     '/cart/:id',              to: 'carts#show',          as: :order_show
  get     '/cart/:id/edit',         to: 'carts#edit',          as: :order_edit
  patch   '/cart/:id',              to: 'carts#update',        as: :order_update
  delete  '/cart/:id/delete',       to: 'carts#destroy',       as: :order_destroy

  get     '/play',                  to: 'play#index',         as: :play

  get     '/events',                to: 'events#index',       as: :event
  get     '/events',                to: 'events#index',       as: :events
  get     '/events/new',            to: 'events#new',         as: :events_new
  post    '/events',                to: 'events#create',      as: :events_create
  get     '/events/:id',            to: 'events#show',        as: :events_show
  get     '/events/:id/edit',       to: 'events#edit',        as: :events_edit
  patch   '/events/:id',            to: 'events#update',      as: :events_update
  delete  '/events/:id/delete',     to: 'events#destroy',     as: :events_destroy

  get     '/contact',               to: 'contact#index',      as: :contact

end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
    @products = Product.all
    @products.to_a.reverse!
  end

  def new
    if session[:current_session_id]
      @product = Product.new
    else
      redirect_to root_path
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      # @product.user = current_user
      # @users = User.all
      # @users = @users.map {|user| user if user.confirmed? }
      # @users.each do |user|
      #   unless !user
      #     Resque.enqueue(EmailNewsJob, @product.id, user.id)
      #   end
      # end
      redirect_to products_path, notice: "Product has been created!"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
    @order_item = OrderItem.new
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price_cents, :stock_quantity)
  end

  # *****************




# def show
#   find_product
#   @categories = @product.categories
#   @reviews = @product.reviews
#
#   # #added by Holly
#   @current_order = Order.where(:session_id => @current_session_id, :current_state => "pending")
#   if @current_order.size == 0
#     @order = Order.new(:session_id => @current_session_id, :current_state => "pending")
#     @order.save
#   else
#     #if current_order size == 1
#     @order = @current_order[0]
#   end
#
#   if OrderItem.find_by(:product_id => @product.id, :order_id => @order.id).present?
#     @order_item = OrderItem.find_by(:product_id => @product.id)
#   else
#     @order_item = OrderItem.new
#   end
# end

# def add_to_cart
#   find_product
#
#   # #added by Holly
#   @current_order = Order.where(:session_id => @current_session_id, :current_state => "pending")
#   if @current_order.size == 0
#     @order = Order.new(:session_id => @current_session_id, :current_state => "pending")
#     @order.save
#   else
#     #if current_order size == 1
#     @order = @current_order[0]
#   end
#
#   if OrderItem.find_by(:product_id => @product.id, :order_id => @order.id).present?
#     @order_item = OrderItem.find_by(:product_id => @product.id)
#   else
#     @order_item = OrderItem.new(:product_id => @product.id, :order_id => @order.id)
#
#   end
#   @order_item.save
# end





# def edit
#   find_product
#   if session[:user_id]
#     @categories = Category.all
#   else
#     redirect_to home_path
#   end
# end
#
# def update
#   @categories = Category.all
#   find_product
#   if @product.update(product_params) && session[:user_id]
#     #put this into myaccount dashboard once that's been created
#     redirect_to dashboard_path(current_user), notice: "Product has been updated!"
#   else
#     render "edit"
#   end
# end
#
# # products can now be 'retired' so can delete this
# def destroy
#   if find_product.destroy
#     redirect_to dashboard_path(current_user), notice: "Product has been deleted!"
#   else
#     render "delete", notice: "Try again."
#   end
# end

private


def find_product
  @product = Product.find(params[:id])
end

end

app/helpers/shop_helper.rb
module ShopHelper
  def out_of_stock?(stock)
    if stock == 0
      "Out of Stock"
    end
  end
end

app/views/shop/edit.html.erb
<%= bootstrap_form_for @product, url: {action: "update"} do |f| %>
  <%= f.text_field :name, class: "form-control", placeholder: "Name"  %>
  <%= f.text_area :description, class: "form-control", placeholder: "Content", rows: "20" %>
  <%= f.submit "Save", class: "btn btn-default"%>
<% end %>

app/views/shop/index.html.erb
<h1>Slapong Products</h1>
<% if admin? %>
  <%= link_to "Create a New Product", products_new_path, class:"btn btn-primary" %>
<% end %>

<img src="http://fakeimg.pl/1140x300/" alt="...">

<% @products.each do |product| %>
  <div class="row">
    <!-- Blog post Content Column -->
    <div class="col-lg-12">
      <!-- Blog post -->
      <div class="row">
        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <img src="..." alt="...">
            <div class="caption">
              <h3><%= link_to product.name, products_show_path(product) %></h3>
              <p>
                Price: <%= product.price_cents %>
                In stock: <%= product.stock_quantity %>
              </p>
              <%= product.description %>
              <%= link_to "Add to cart", order_items_new_path, class:"btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shop/new.html.erb
<%= bootstrap_form_for(@product) do |f| %>
  <%= f.text_field :name, class: "form-control", placeholder: "Name"  %>
  <%= f.text_area :description, class: "form-control", placeholder: "Description", rows: "20" %>
  <%= f.number_field :price_cents, class: "form-control", placeholder: "Price", icon: "usd" %>
  <%= f.number_field :stock_quantity, class: "form-control", placeholder: "Quantity in stock", rows: "20" %>
  <%= f.submit "Save", class: "btn btn-default"%>
<% end %>

app/views/shop/show.html.erb
<!-- <% if @current_user && @current_user.admin %>
  <%= link_to "Edit", edit_product_path(@product), class:"btn btn-default" %>
  <%= link_to "Delete", product_path(@product), method: :delete, class:"btn btn-default" %>
<% end %> -->
<% if admin? %>
  <%= link_to "Edit", products_edit_path(@product), class:"btn btn-default" %>
  <%= link_to "Delete", products_destroy_path(@product), method: :delete, class:"btn btn-default" %>
<% end %>

<div class="row">
  <!-- Blog product Content Column -->
  <div class="col-lg-8">
    <!-- Blog product -->
    <!-- Title -->
    <h1><%= @product.name %></h1>
    <hr>
    <div class="row">
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="..." alt="...">
        </a>
      </div>
      ...
    </div>
    <!-- Date/Time -->
    <!-- product Content -->
      Price: <%= @product.price_cents %>
      Quantity: <%= @product.stock_quantity %>
    </p>
    <%= @product.description %>
    <hr>
    <h2>Add to Cart:</h2>
    <%= bootstrap_form_for(@order_item) do |f| %>
      <%= f.number_field :quantity, class: "form-control", placeholder: "Quantity", min: 1, max: @product.stock_quantity   %>
      <%= f.hidden_field :subtotal, class: "form-control", :value => @product.stock_quantity  %>
      <%= f.hidden_field :product_id, :value => @product.id %>
      <%= f.submit "Add to Cart", class: "btn btn-default"%>
    <% end %>

  </div>
  <hr>
</div>

<div id="disqus_thread"></div>
  <script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'slapong'; // required: replace example with your forum shortname
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<br>
<br>