config/routes.rb
Rails.application.routes.draw do

  get     '/',                      to: 'home#index',         as: :root
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  get     '/blog',                  to: 'blog#index',         as: :post
  get     '/blog',                  to: 'blog#index',         as: :posts
  get     '/blog/new',              to: 'blog#new',           as: :posts_new
  post    '/blog',                  to: 'blog#create',        as: :posts_create
  get     '/blog/:id',              to: 'blog#show',          as: :posts_show
  get     '/blog/:id/edit',         to: 'blog#edit',          as: :posts_edit
  patch   '/blog/:id',              to: 'blog#update',        as: :posts_update
  delete  '/blog/:id/delete',       to: 'blog#destroy',       as: :posts_destroy

  get     '/shop',                  to: 'shop#index',         as: :product
  get     '/shop',                  to: 'shop#index',         as: :products
  get     '/shop/new',              to: 'shop#new',           as: :products_new
  post    '/shop',                  to: 'shop#create',        as: :products_create
  get     '/shop/:id',              to: 'shop#show',          as: :products_show
  get     '/shop/:id/edit',         to: 'shop#edit',          as: :products_edit
  patch   '/shop/:id',              to: 'shop#update',        as: :products_update
  delete  '/shop/:id/delete',       to: 'shop#destroy',       as: :products_destroy

  get     '/cart',                  to: 'carts#index',         as: :order
  get     '/cart/new',              to: 'carts#new',           as: :order_new
  post    '/cart',                  to: 'carts#create',        as: :order_create
  get     '/cart/:id',              to: 'carts#show',          as: :order_show
  get     '/cart/:id/edit',         to: 'carts#edit',          as: :order_edit
  patch   '/cart/:id',              to: 'carts#update',        as: :order_update
  delete  '/cart/:id/delete',       to: 'carts#destroy',       as: :order_destroy

  get     '/play',                  to: 'play#index',         as: :play

  get     '/events',                to: 'events#index',       as: :event
  get     '/events',                to: 'events#index',       as: :events
  get     '/events/new',            to: 'events#new',         as: :events_new
  post    '/events',                to: 'events#create',      as: :events_create
  get     '/events/:id',            to: 'events#show',        as: :events_show
  get     '/events/:id/edit',       to: 'events#edit',        as: :events_edit
  patch   '/events/:id',            to: 'events#update',      as: :events_update
  delete  '/events/:id/delete',     to: 'events#destroy',     as: :events_destroy

  get     '/contact',               to: 'contact#index',      as: :contact

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    @events.to_a.reverse!
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      # @users = User.all
      # @users = @users.map {|user| user if user.confirmed? }
      # @users.each do |user|
      #   unless !user
      #     Resque.enqueue(EmailNewsJob, @event.id, user.id)
      #   end
      # end
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date, :end_time, :start_time, :street_address, :city, :state, :zip)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<%= bootstrap_form_for @event, url: {action: "update"} do |f| %>
  <%= f.text_field :title, class: "form-control", placeholder: "Title"  %>
  <%= f.text_area :description, class: "form-control", placeholder: "Description", rows: "20" %>
  <%= f.date_select :date, class: "form-control", placeholder: "Date"  %>
  <%= f.time_select :start_time, class: "form-control", placeholder: "Start Time", rows: "20" %>
  <%= f.time_select :end_time, class: "form-control", placeholder: "End Time", rows: "20" %>
  <%= f.text_field :street_address, class: "form-control", placeholder: "Street Address"  %>
  <%= f.text_field :city, class: "form-control", placeholder: "City", rows: "20" %>
  <%= f.text_field :state, class: "form-control", placeholder: "State", rows: "20" %>
  <%= f.text_field :zip, class: "form-control", placeholder: "Zip", rows: "20" %>
  <%= f.submit "Save", class: "btn btn-default"%>
<% end %>

app/views/events/index.html.erb
<h1>Slap Events</h1>

<% if admin? %>
  <%= link_to "Create an Event", events_new_path, class:"btn btn-primary" %>
<% end %>

<% @events.each do |event| %>
  <div class="row">
    <!-- Event Content Column -->
    <div class="col-lg-12">
      <!-- Blog event -->
      <!-- Title -->
      <h2><%= link_to event.title, events_show_path(event) %></h2>
      <hr>
      <!-- Date/Time -->
      <p><span class="glyphicon glyphicon-calendar"></span> <%= event.date.strftime("%A, %B %e, %Y") %>
      <p><span class="glyphicon glyphicon-time"></span><%= event.start_time.strftime("%l:%M %P") %> - <%= event.end_time.strftime("%l:%M %P (%Z)") %></p></p>
      <p><span class="glyphicon glyphicon-envelope"></span>
        <%= event.street_address %>
        <%= event.city %>,
        <%= event.state %><%= event.zip %>
      </p>
      <hr>
      <!-- Preview Image -->
      <!-- Event Content -->
      <p><%= event.description[0..350] %>... <%= link_to "read more", events_show_path(event) %></p>
      <hr>
      <!-- Event Comments -->
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<%= bootstrap_form_for(@event) do |f| %>
  <%= f.text_field :title, class: "form-control", placeholder: "Title"  %>
  <%= f.text_area :description, class: "form-control", placeholder: "Description", rows: "20" %>
  <%= f.date_select :date, class: "form-control", placeholder: "Date"  %>
  <%= f.time_select :start_time, class: "form-control", placeholder: "Start Time", rows: "20" %>
  <%= f.time_select :end_time, class: "form-control", placeholder: "End Time", rows: "20" %>
  <%= f.text_field :street_address, class: "form-control", placeholder: "Street Address"  %>
  <%= f.text_field :city, class: "form-control", placeholder: "City", rows: "20" %>
  <%= f.text_field :state, class: "form-control", placeholder: "State", rows: "20" %>
  <%= f.text_field :zip, class: "form-control", placeholder: "Zip", rows: "20" %>
  <%= f.submit "Save", class: "btn btn-default"%>
<% end %>

app/views/events/show.html.erb
<div class="row">
  <!-- Event Content Column -->
  <div class="col-lg-12">
    <!-- Blog event -->
    <!-- Title -->
    <h1><%= @event.title %></h1>
    <hr>
    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-calendar"></span> <%= @event.date.strftime("%A, %B %e, %Y") %>
    <p><span class="glyphicon glyphicon-time"></span><%= @event.start_time.strftime("%l:%M %P") %> - <%= @event.end_time.strftime("%l:%M %P (%Z)") %></p></p>
    <p><span class="glyphicon glyphicon-envelope"></span>
      <%= @event.street_address %>
      <%= @event.city %>,
      <%= @event.state %><%= @event.zip %>
    </p>
    <hr>
    <!-- Preview Image -->

    <!-- Event Content -->
    <p><%= @event.description %></p>
    <hr>
    <!-- Event Comments -->
  </div>
</div>

<% if admin? %>
  <%= link_to "Edit", events_edit_path(@event), class:"btn btn-default" %>
  <%= link_to "Delete", events_destroy_path(@event), method: :delete, class:"btn btn-default" %>
<% end %>

<div id="disqus_thread"></div>
  <script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'slapong'; // required: replace example with your forum shortname
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>