config/routes.rb
Rails.application.routes.draw do

  get     '/',                      to: 'home#index',         as: :root
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  get     '/blog',                  to: 'blog#index',         as: :post
  get     '/blog',                  to: 'blog#index',         as: :posts
  get     '/blog/new',              to: 'blog#new',           as: :posts_new
  post    '/blog',                  to: 'blog#create',        as: :posts_create
  get     '/blog/:id',              to: 'blog#show',          as: :posts_show
  get     '/blog/:id/edit',         to: 'blog#edit',          as: :posts_edit
  patch   '/blog/:id',              to: 'blog#update',        as: :posts_update
  delete  '/blog/:id/delete',       to: 'blog#destroy',       as: :posts_destroy

  get     '/shop',                  to: 'shop#index',         as: :product
  get     '/shop',                  to: 'shop#index',         as: :products
  get     '/shop/new',              to: 'shop#new',           as: :products_new
  post    '/shop',                  to: 'shop#create',        as: :products_create
  get     '/shop/:id',              to: 'shop#show',          as: :products_show
  get     '/shop/:id/edit',         to: 'shop#edit',          as: :products_edit
  patch   '/shop/:id',              to: 'shop#update',        as: :products_update
  delete  '/shop/:id/delete',       to: 'shop#destroy',       as: :products_destroy

  get     '/cart',                  to: 'carts#index',         as: :order
  get     '/cart/new',              to: 'carts#new',           as: :order_new
  post    '/cart',                  to: 'carts#create',        as: :order_create
  get     '/cart/:id',              to: 'carts#show',          as: :order_show
  get     '/cart/:id/edit',         to: 'carts#edit',          as: :order_edit
  patch   '/cart/:id',              to: 'carts#update',        as: :order_update
  delete  '/cart/:id/delete',       to: 'carts#destroy',       as: :order_destroy

  get     '/play',                  to: 'play#index',         as: :play

  get     '/events',                to: 'events#index',       as: :event
  get     '/events',                to: 'events#index',       as: :events
  get     '/events/new',            to: 'events#new',         as: :events_new
  post    '/events',                to: 'events#create',      as: :events_create
  get     '/events/:id',            to: 'events#show',        as: :events_show
  get     '/events/:id/edit',       to: 'events#edit',        as: :events_edit
  patch   '/events/:id',            to: 'events#update',      as: :events_update
  delete  '/events/:id/delete',     to: 'events#destroy',     as: :events_destroy

  get     '/contact',               to: 'contact#index',      as: :contact

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @posts = Post.all
    @posts.to_a.reverse!
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      # @users = User.all
      # @users = @users.map {|user| user if user.confirmed? }
      # @users.each do |user|
      #   unless !user
      #     Resque.enqueue(EmailNewsJob, @post.id, user.id)
      #   end
      # end
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<%= bootstrap_form_for @post, url: {action: "update"} do |f| %>
  <%= f.text_field :title, class: "form-control", placeholder: "Title"  %>
  <%= f.text_field :body, class: "form-control", placeholder: "Body" %>
  <%= f.submit "Save", class: "btn btn-default"%>
<% end %>

app/views/blog/index.html.erb
<h1>Slapblog</h1>
<% @posts.each do |post| %>
  <div class="row">
    <!-- Blog post Content Column -->
    <div class="col-lg-12">
      <!-- Blog post -->
      <div class="row">
        <div class="col-xs-6 col-md-3">
          <a href="#" class="thumbnail">
            <img src="..." alt="...">
          </a>
        </div>
        ...
      </div>
      <!-- Title -->
      <h2><%= link_to post.title, posts_show_path(post) %></h2>
      <hr>
      <!-- Date/Time -->
      <p><span class="glyphicon glyphicon-time"></span> <%= post.created_at %></p>
      <hr>
      <!-- Preview Image -->
      <!-- post Content -->
      <p class="lead"><%= post.body[0..350] %>... <%= link_to "read more", posts_show_path(post) %></p>
      <hr>
      <!-- Blog Comments -->
    </div>
  </div>
<% end %>

<% if admin? %>
  <%= link_to "Create a New post", posts_new_path, class:"btn btn-primary" %>
<% end %>

app/views/blog/new.html.erb
<%= bootstrap_form_for(@post) do |f| %>
  <%= f.text_field :title, class: "form-control", placeholder: "Title"  %>
  <%= f.text_area :body, class: "form-control", placeholder: "Body", rows: "20" %>
  <%= f.submit "Save", class: "btn btn-default"%>
<% end %>

app/views/blog/show.html.erb
<% if admin? %>
  <%= link_to "Edit", posts_edit_path(@post), class:"btn btn-default" %>
  <%= link_to "Delete", posts_destroy_path(@post), method: :delete, class:"btn btn-default" %>
<% end %>

<div class="row">
  <!-- Blog post Content Column -->
  <div class="col-lg-8">
    <!-- Blog post -->
    <!-- Title -->
    <h1><%= @post.title %></h1>
    <hr>
    <div class="row">
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="..." alt="...">
        </a>
      </div>
      ...
    </div>
    <!-- Date/Time -->
    <!-- post Content -->
    <p class="lead"><%= @post.body %></p>
  </div>
</div>

<div id="disqus_thread"></div>
  <script type="text/javascript">
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'slapong'; // required: replace example with your forum shortname
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<br>
<br>